server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

# 数据源
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    # 静态资源url
#    static-path-pattern: /static/**
  # 热部署生效
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  # 静态资源
#  resources:
#    static-locations: file:/root/webapps/assets
  # 数据源
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      #基本属性
      jdbc-url: jdbc:mysql://aliyun:3306/knowledge?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 644886
      default-auto-commit: false
      default-transaction-isolation: 4 # 2:读已提交 4：可重复读
      #配置初始化大小/最小/最大
      initial-size: 2
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  servlet:
    #文件上传
    multipart:
      #是否启用Spring MVC 多分部上传功能
      enabled: true
      #将文件写入磁盘的阀值。值可以使用后缀“ MB ”或“ KB ” 来表示兆字节或字节大小
      file-size-threshold: 0
      #location: D:/tmp
      max-file-size: 5MB
      max-request-size: 20MB
      #是否延迟多部件文件请求的参数和文件的解析
      resolve-lazily: false

      #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis配置
mybatis:
  type-aliases-package: com.pier.bean

#logging:
#  config: classpath:logback.xml
##  level: error

#1.4.2中不能打包，要注掉
#app:
#  java:
#    # 读取maven的配置
#    version: @java.version@